const cloud = require('wx-server-sdk')
const PDFDocument = require('pdfkit')

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()
const collection = db.collection('inspection_reports')

function printable(value) {
  return String(value || '').replace(/[^\x20-\x7e]/g, '?')
}

function createReportPdf(report) {
  return new Promise((resolve, reject) => {
    const document = new PDFDocument({ size: 'A4', margin: 48 })
    const chunks = []
    document.on('data', chunk => chunks.push(chunk))
    document.on('error', reject)
    document.on('end', () => resolve(Buffer.concat(chunks)))

    document.fontSize(20).fillColor('#102a43').text('Machine Vision Inspection Report')
    document.moveDown(0.6)
    document.fontSize(10).fillColor('#334155')
    document.text(`Report ID: ${printable(report.id)}`)
    document.text(`Mode: ${printable(report.mode)}`)
    document.text(`Inspection time: ${printable(report.time)}`)
    document.moveDown()
    document.fontSize(14).fillColor('#0f766e').text('Inspection Summary')
    document.fontSize(11).fillColor('#111827')
    document.text(`Total: ${printable(report.total)}    PASS: ${printable(report.passed)}    FAIL: ${printable(report.failed)}    Yield: ${printable(report.yieldRate)}`)
    document.moveDown()
    document.fontSize(14).fillColor('#0f766e').text('Inspection Result')
    document.fontSize(12).fillColor(report.verdict === 'FAIL' ? '#dc2626' : '#15803d')
    document.text(printable(report.result))
    document.moveDown()
    document.fontSize(14).fillColor('#0f766e').text('Detected Defects')
    document.fontSize(11).fillColor('#111827')
    document.text(printable((report.defects || []).join(', ') || 'None'))
    document.moveDown()
    document.fontSize(9).fillColor('#64748b').text('Generated by Embedded Machine Vision Defect Detection System')
    document.end()
  })
}

exports.main = async (event) => {
  const action = event.action || 'list'
  if (action === 'list') {
    const result = await collection.orderBy('time', 'desc').limit(100).get()
    return { reports: result.data }
  }
  if (action === 'detail') {
    const result = await collection.where({ id: event.id }).limit(1).get()
    return { report: result.data[0] || null }
  }
  if (action === 'upsert') {
    if (!event.report || !event.report.id) throw new Error('report.id is required')
    const previous = await collection.where({ id: event.report.id }).limit(1).get()
    if (previous.data.length) {
      await collection.doc(previous.data[0]._id).set({ data: event.report })
    } else {
      await collection.add({ data: event.report })
    }
    return { ok: true }
  }
  if (action === 'generatePdf') {
    const result = await collection.where({ id: event.id }).limit(1).get()
    const report = result.data[0] || event.report
    if (!report || !report.id) throw new Error('Report not found.')
    const fileContent = await createReportPdf(report)
    const upload = await cloud.uploadFile({
      cloudPath: `inspection-reports/${printable(report.id)}-${Date.now()}.pdf`,
      fileContent,
    })
    return { fileID: upload.fileID }
  }
  throw new Error(`Unsupported action: ${action}`)
}
